version: "3.1"
services:
  jenkins:
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    # Custom Jenkins image
    image: localhost:5000/jenkins-controller
  jenkins-agent:
    container_name: jenkins-agent
    restart: always
    environment:
      - "JENKINS_URL=http://jenkins:8080"
    image: localhost:5000/jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
